"""
Generated by CubeBuilder-FEKit

omm_nonbonded.py

This module updates nonbonded forces for OpenMM simulation.

Author: Jumin Lee
Contact: jumin@molcube.com
"""

from openmm import *
from openmm.app import *
from openmm.unit import *

NONBONDED_FORCE_GROUP = 6

def updateNonbonded(system, ligand_info, inputs):
    nbforce1 = nbforce2 = nbforce3 = None
    for force in system.getForces():
        if force.getForceGroup() == NONBONDED_FORCE_GROUP:
            if type(force).__name__ == 'NonbondedForce':
                nbforce1 = force
            elif type(force).__name__ == 'CustomNonbondedForce':
                if force.getNumTabulatedFunctions() == 2:
                    nbforce3 = force
                else:
                    nbforce2 = force

    # UPDATE ELECTROSTATIC AND ENVIRONMENT-ENVIRONMENT INTERACTIONS
    nbforce1.setUseDispersionCorrection(inputs.lj_lrc)
    nbforce1.setNonbondedMethod(getattr(nbforce1, inputs.nb_method))
    nbforce1.setCutoffDistance(inputs.r_off)

    if inputs.sw_method != 'NONE':
        if inputs.r_on > inputs.r_off:
            raise ValueError('switchDistance is too large compared '
                             'to the cutoff!')
        if inputs.r_on < 0.0 * nanometer:
            raise ValueError('siwtchDistance must be non-negative!')
        if inputs.sw_method == 'POTENTIAL-BASED':
            nbforce1.setUseSwitchingFunction(True)
            nbforce1.setSwitchingDistance(inputs.r_on)

    nbforce2.setUseLongRangeCorrection(inputs.lj_lrc)
    nbforce2.setCutoffDistance(inputs.r_off)
    if inputs.nb_method in ('PME', 'Ewald', 'CutoffPeriodic'):
        nbforce2.setNonbondedMethod(nbforce2.CutoffPeriodic)
    elif inputs.nb_method in ('NoCutoff', 'CutoffNonPeriodic'):
        nbforce2.setNonbondedMethod(getattr(nbforce2, inputs.nb_method))
    else:
        raise ValueError('Unsupported nonbonded method')
    if inputs.sw_method == 'POTENTIAL-BASED':
        nbforce2.setUseSwitchingFunction(True)
        nbforce2.setSwitchingDistance(inputs.r_on)

    if inputs.sw_method == 'FORCE-BASED':
        efunc = get_vfswitch_softcore_energy_function(inputs.nb_comb_rule)
        nbforce2.setEnergyFunction(efunc)
        nbforce2.addGlobalParameter('Ron', inputs.r_on)
        nbforce2.addGlobalParameter('Roff', inputs.r_off)
        if nbforce3:
            efunc = get_vfswitch_energy_function()
            nbforce3.setEnergyFunction(efunc+'sigma=sig(type1,type2); epsilon=eps(type1,type2);')
            nbforce3.addGlobalParameter('Ron', inputs.r_on)
            nbforce3.addGlobalParameter('Roff', inputs.r_off)
        else:
            nbforce3 = create_vfswitch_force(nbforce1, ligand_info, inputs)
            system.addForce(nbforce3)
        nbforce4, nbforce5 = create_vfswitch14_force(nbforce1, ligand_info, inputs)
        system.addForce(nbforce4)
        system.addForce(nbforce5)

    if nbforce3:
        nbforce3.setUseLongRangeCorrection(inputs.lj_lrc)
        nbforce3.setCutoffDistance(inputs.r_off)
        if inputs.nb_method in ('PME', 'Ewald', 'CutoffPeriodic'):
            nbforce3.setNonbondedMethod(nbforce3.CutoffPeriodic)
        elif inputs.nb_method in ('NoCutoff', 'CutoffNonPeriodic'):
            nbforce3.setNonbondedMethod(getattr(nbforce3, inputs.nb_method))
        else:
            raise ValueError('Unsupported nonbonded method')
        if inputs.sw_method == 'POTENTIAL-BASED':
            nbforce3.setUseSwitchingFunction(True)
            nbforce3.setSwitchingDistance(inputs.r_on)

def get_vfswitch_energy_function():
    efunc = 'select(step(r-Ron),(cr12*rjunk12 - cr6*rjunk6),' \
            '(acoef/r^12-bcoef/r^6-acoef/onoff^6+bcoef/onoff^3));' \
            'cr12 = acoef*ofdif6;' \
            'cr6  = bcoef*ofdif3;' \
            'rjunk12 = (1.0/r^6-1.0/Roff6)^2;' \
            'rjunk6  = (1.0/r^3-1.0/Roff3)^2;' \
            'ofdif6 = Roff6/(Roff6 - Ron^6);' \
            'ofdif3 = Roff3/(Roff3 - Ron^3);' \
            'onoff = Ron*Roff;' \
            'Roff6 = Roff^6;' \
            'Roff3 = Roff^3;' \
            'acoef = 4.0*epsilon*sigma^12;' \
            'bcoef = 4.0*epsilon*sigma^6;'
    return efunc

def get_vfswitch_softcore_energy_function(nb_comb_rule):
    efunc = 'select(step(r-r_LJ), select(step(r-Ron),' \
            '(cr12*rjunk12 - cr6*rjunk6),' \
            '(acoef/r^12 - bcoef/r^6 - V_offset)),' \
            'U_sterics_quad);' \
            'U_sterics_quad = U_sterics_cut + Force * (((r - r_LJ)^2)/2 - (r - r_LJ));' \
            'U_sterics_cut = acoef/(r_LJ^12) - bcoef/(r_LJ^6) - V_offset;' \
            'Force = 12*acoef/(r_LJ^13) - 6*bcoef/(r_LJ^7);' \
            'r_LJ = softcore_alpha*((26/7)*(sigma^6)*lambda_sterics_deprecated)^(1/6);' \
            'V_offset = acoef/onoff^6 - bcoef/onoff^3;' \
            'onoff = Ron * Roff;' \
            'cr12 = acoef * ofdif6;' \
            'cr6  = bcoef * ofdif3;' \
            'rjunk12 = (1.0/r^6 - 1.0/Roff^6)^2;' \
            'rjunk6  = (1.0/r^3 - 1.0/Roff^3)^2;' \
            'ofdif6 = Roff^6 / (Roff^6 - Ron^6);' \
            'ofdif3 = Roff^3 / (Roff^3 - Ron^3);' \
            'acoef = 4*epsilon*sigma^12;' \
            'bcoef = 4*epsilon*sigma^6;' \
            'lambda_sterics_deprecated = stateB_interaction*(1.0 - lambda_sterics_insert) + ' \
            'stateA_interaction*lambda_sterics_delete;' \
            'epsilon = (1-lambda_sterics)*epsilonA + lambda_sterics*epsilonB;' \
            'sigma = (1-lambda_sterics)*sigmaA + lambda_sterics*sigmaB;' \
            'lambda_sterics = core_interaction*lambda_sterics_core + ' \
            'stateB_interaction*lambda_sterics_insert + ' \
            'stateA_interaction*lambda_sterics_delete;' \
            'core_interaction = delta(unique_stateA1+unique_stateA2+unique_stateB1+unique_stateB2);' \
            'stateB_interaction = max(unique_stateB1, unique_stateB2);' \
            'stateA_interaction = max(unique_stateA1, unique_stateA2);' \
            'epsilonB = sqrt(epsilonB1*epsilonB2);' \
            'epsilonA = sqrt(epsilonA1*epsilonA2);'

    if nb_comb_rule == 1:
        efunc += 'sigmaB = 0.5*(sigmaB1 + sigmaB2);'
        efunc += 'sigmaA = 0.5*(sigmaA1 + sigmaA2);'
    elif nb_comb_rule == 2:
        efunc += 'sigmaB = sqrt(sigmaB1*sigmaB2);'
        efunc += 'sigmaA = sqrt(sigmaA1*sigmaA2);'

    return efunc

def create_vfswitch_force(nbforce, ligand_info, inputs):
    efunc = get_vfswitch_energy_function()
    efunc += 'epsilon = sqrt(epsilon1*epsilon2);'
    if inputs.nb_comb_rule == 1:
        efunc += 'sigma = (sigma1+sigma2)/2.0;'
    elif inputs.nb_comb_rule == 2:
        efunc += 'sigma = sqrt(sigma1*sigma2);'

    force = CustomNonbondedForce(efunc)
    force.addGlobalParameter('Ron', inputs.r_on)
    force.addGlobalParameter('Roff', inputs.r_off)
    force.addPerParticleParameter('sigma')
    force.addPerParticleParameter('epsilon')
    force.setForceGroup(NONBONDED_FORCE_GROUP)

    ligand_atoms = set(atom for atom_list in ligand_info.values() for atom in atom_list)
    environment_atoms = list()
    for i in range(nbforce.getNumParticles()):
        charge, sigma, epsilon = nbforce.getParticleParameters(i)
        nbforce.setParticleParameters(i, charge, sigma, 0.0)
        force.addParticle([sigma, epsilon])
        if not i in ligand_atoms:
            environment_atoms.append(i)
    for i in range(nbforce.getNumExceptions()):
        atom1, atom2 = nbforce.getExceptionParameters(i)[:2]
        force.addExclusion(atom1, atom2)

    force.addInteractionGroup(environment_atoms, environment_atoms)

    return force

def create_vfswitch14_force(nbforce, ligand_info, inputs):
    efunc1 = get_vfswitch_energy_function()
    efunc2 = get_vfswitch_energy_function()
    efunc2 += 'epsilon = (1-lambda_sterics_core)*epsilonA + lambda_sterics_core*epsilonB;'
    efunc2 += 'sigma = (1-lambda_sterics_core)*sigmaA + lambda_sterics_core*sigmaB;'

    nb14_force1 = CustomBondForce(efunc1)
    nb14_force1.setForceGroup(NONBONDED_FORCE_GROUP)
    nb14_force1.addGlobalParameter('Ron', inputs.r_on)
    nb14_force1.addGlobalParameter('Roff', inputs.r_off)
    nb14_force1.addPerBondParameter('sigma')
    nb14_force1.addPerBondParameter('epsilon')

    nb14_force2 = CustomBondForce(efunc2)
    nb14_force2.setForceGroup(NONBONDED_FORCE_GROUP)
    nb14_force2.addGlobalParameter('lambda_sterics_core', 0.0)
    nb14_force2.addGlobalParameter('Ron', inputs.r_on)
    nb14_force2.addGlobalParameter('Roff', inputs.r_off)

    for parameter in ['sigmaA', 'epsilonA', 'sigmaB', 'epsilonB']:
        nb14_force2.addPerBondParameter(parameter)

    exception_list = dict()
    for i in range(nbforce.getNumExceptionParameterOffsets()):
        param_name, exception_index, charge_scale, sigma_scale, epsilon_scale = nbforce.getExceptionParameterOffset(i)
        if param_name != 'lambda_sterics_core': continue
        atom1, atom2, charge, sigma, epsilon = nbforce.getExceptionParameters(exception_index)
        sigmaB   = sigma + sigma_scale*nanometers
        epsilonB = epsilon + epsilon_scale*kilojoules_per_mole
        exception_list[exception_index] = (sigma, epsilon, sigmaB, epsilonB)
        nbforce.setExceptionParameterOffset(i, param_name, exception_index, charge_scale, 0, 0)

    for i in range(nbforce.getNumExceptions()):
        atom1, atom2, charge, sigma, epsilon = nbforce.getExceptionParameters(i)
        if not epsilon: continue
        nbforce.setExceptionParameters(i, atom1, atom2, charge, 0.1, 0.0)
        if i in exception_list:
            sigmaA, epsilonA, sigmaB, epsilonB = exception_list[i]
            nb14_force2.addBond(atom1, atom2, [sigmaA, epsilonA, sigmaB, epsilonB])
        else:
            nb14_force1.addBond(atom1, atom2, [sigma, epsilon])

    return nb14_force1, nb14_force2

